site_name: !ENV [SITE_NAME, "Sample Site"]
site_url: !ENV [SITE_URL, "https://example.com/"]
site_dir: !ENV [SITE_DIR, "site"]
docs_dir: !ENV [DOCS_DIR, "processed"]
repo_url: !ENV [repo_url, ""]

nav:
  - "Home": "index.md"
  - "About": "about.md"
  - "No Includes": "no-includes.md"
  - "Sub Section1":
      - "Home": "sub1/index.md"
      - "About": "sub1/about.md"
      - "No Includes": "sub1/no-includes.md"
theme: readthedocs
