site_name: !ENV [SITE_NAME, "My Docs"]
site_url: !ENV [SITE_URL, "https://example.com/"]
site_dir: !ENV [SITE_NAME, "site"]
docs_dir: !ENV [DOCS_DIR, "processed"]

nav:
  - Home: index.md
  - About: about.md
  - Contact Us: contact-us.md
  - Products: products.md
  - Services: services.md
  - License: license.md
theme: readthedocs
