site_name: My Docs
site_url: https://example.com/
site_dir: !ENV [SITE_NAME, "My default site name"]

nav:
  - Home: index.md
  - About: about.md
  - Contact Us: contact-us.md
  - Products: products.md
  - Services: services.md
  - License: license.md
theme: readthedocs
